# Form implementation generated from reading ui file 'dorm.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 474)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1,\n"
"        stop: 0 #667eea, stop: 0.5 #764ba2, stop: 1 #f093fb);\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: 2px solid #ffffff;\n"
"    background: rgba(255, 255, 255, 0.92);\n"
"    border-radius: 12px;\n"
"    margin: 8px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    alignment: center;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #6a11cb, stop: 1 #2575fc);\n"
"    color: white;\n"
"    border: 1px solid #5d00ff;\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom: none;\n"
"    min-width: 120px;\n"
"    padding: 12px 16px;\n"
"    margin: 2px;\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #ffffff, stop: 1 #f8f9fa);\n"
"    color: #2c3e50;\n"
"    border-color: #3498db;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #8e2de2, stop: 1 #4a00e0);\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #2c3e50;\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #667eea, stop: 1 #764ba2);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 10px 20px;\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #764ba2, stop: 1 #667eea);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #5a3d8a, stop: 1 #4a2c6d);\n"
"}\n"
"\n"
"QGroupBox {\n"
"    background: rgba(255, 255, 255, 0.85);\n"
"    border: 2px solid #bdc3c7;\n"
"    border-radius: 10px;\n"
"    margin-top: 12px;\n"
"    padding-top: 12px;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"    color: #2c3e50;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #667eea, stop: 1 #764ba2);\n"
"    color: white;\n"
"    padding: 6px 16px;\n"
"    border-radius: 6px;\n"
"    margin-top: -8px;\n"
"}\n"
"\n"
"QListWidget, QTableWidget, QTreeWidget, QTextBrowser, QTextEdit, QLineEdit {\n"
"    background: rgba(255, 255, 255, 0.95);\n"
"    border: 2px solid #bdc3c7;\n"
"    border-radius: 8px;\n"
"    padding: 6px;\n"
"    font-size: 12px;\n"
"    color: #2c3e50;\n"
"    selection-background-color: #3498db;\n"
"    selection-color: white;\n"
"}\n"
"\n"
"QListWidget::item:hover, QTreeWidget::item:hover {\n"
"    background: #ecf0f1;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background: rgba(255, 255, 255, 0.95);\n"
"    border: 2px solid #bdc3c7;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-size: 12px;\n"
"    color: #2c3e50;\n"
"    min-width: 120px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    width: 20px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"    border-left: 5px solid transparent;\n"
"    border-right: 5px solid transparent;\n"
"    border-top: 5px solid #667eea;\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background: white;\n"
"    border: 1px solid #bdc3c7;\n"
"    border-radius: 6px;\n"
"    selection-background-color: #3498db;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #667eea, stop: 1 #764ba2);\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    padding: 8px;\n"
"    border: none;\n"
"}\n"
"\n"
"QStatusBar {\n"
"    background: rgba(255, 255, 255, 0.9);\n"
"    color: #2c3e50;\n"
"    font-size: 11px;\n"
"    border-top: 1px solid #bdc3c7;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.news_tab = QtWidgets.QWidget()
        self.news_tab.setObjectName("news_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.news_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.newsSplitter = QtWidgets.QSplitter(parent=self.news_tab)
        self.newsSplitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.newsSplitter.setObjectName("newsSplitter")
        self.newsList = QtWidgets.QListView(parent=self.newsSplitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.newsList.sizePolicy().hasHeightForWidth())
        self.newsList.setSizePolicy(sizePolicy)
        self.newsList.setObjectName("newsList")
        self.newsContent = QtWidgets.QTextBrowser(parent=self.newsSplitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.newsContent.sizePolicy().hasHeightForWidth())
        self.newsContent.setSizePolicy(sizePolicy)
        self.newsContent.setMaximumSize(QtCore.QSize(16777215, 200))
        self.newsContent.setObjectName("newsContent")
        self.verticalLayout_2.addWidget(self.newsSplitter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.refreshNewsBtn = QtWidgets.QPushButton(parent=self.news_tab)
        self.refreshNewsBtn.setObjectName("refreshNewsBtn")
        self.horizontalLayout.addWidget(self.refreshNewsBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.news_tab, "")
        self.requests_tab = QtWidgets.QWidget()
        self.requests_tab.setObjectName("requests_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.requests_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.requests_tab)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.requestType = QtWidgets.QComboBox(parent=self.requests_tab)
        self.requestType.setObjectName("requestType")
        self.requestType.addItem("")
        self.requestType.addItem("")
        self.requestType.addItem("")
        self.requestType.addItem("")
        self.requestType.addItem("")
        self.requestType.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.requestType)
        self.label_2 = QtWidgets.QLabel(parent=self.requests_tab)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.requestDescription = QtWidgets.QTextEdit(parent=self.requests_tab)
        self.requestDescription.setObjectName("requestDescription")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.requestDescription)
        self.label_3 = QtWidgets.QLabel(parent=self.requests_tab)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.roomNumber = QtWidgets.QLineEdit(parent=self.requests_tab)
        self.roomNumber.setObjectName("roomNumber")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.roomNumber)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.submitRequestBtn = QtWidgets.QPushButton(parent=self.requests_tab)
        self.submitRequestBtn.setObjectName("submitRequestBtn")
        self.verticalLayout_3.addWidget(self.submitRequestBtn)
        self.groupBox = QtWidgets.QGroupBox(parent=self.requests_tab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.myRequestsTable = QtWidgets.QTableWidget(parent=self.groupBox)
        self.myRequestsTable.setObjectName("myRequestsTable")
        self.myRequestsTable.setColumnCount(4)
        self.myRequestsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.myRequestsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.myRequestsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.myRequestsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.myRequestsTable.setHorizontalHeaderItem(3, item)
        self.verticalLayout_4.addWidget(self.myRequestsTable)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.tabWidget.addTab(self.requests_tab, "")
        self.handbook_tab = QtWidgets.QWidget()
        self.handbook_tab.setObjectName("handbook_tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.handbook_tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.handbookTree = QtWidgets.QTreeWidget(parent=self.handbook_tab)
        self.handbookTree.setObjectName("handbookTree")
        self.verticalLayout_5.addWidget(self.handbookTree)
        self.handbookContent = QtWidgets.QTextBrowser(parent=self.handbook_tab)
        self.handbookContent.setObjectName("handbookContent")
        self.verticalLayout_5.addWidget(self.handbookContent)
        self.tabWidget.addTab(self.handbook_tab, "")
        self.profile_tab = QtWidgets.QWidget()
        self.profile_tab.setObjectName("profile_tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.profile_tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.studentInfoGroup = QtWidgets.QGroupBox(parent=self.profile_tab)
        self.studentInfoGroup.setObjectName("studentInfoGroup")
        self.formLayout_2 = QtWidgets.QFormLayout(self.studentInfoGroup)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(parent=self.studentInfoGroup)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.studentName = QtWidgets.QLineEdit(parent=self.studentInfoGroup)
        self.studentName.setObjectName("studentName")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.studentName)
        self.label_5 = QtWidgets.QLabel(parent=self.studentInfoGroup)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.studentRoom = QtWidgets.QLineEdit(parent=self.studentInfoGroup)
        self.studentRoom.setObjectName("studentRoom")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.studentRoom)
        self.label_6 = QtWidgets.QLabel(parent=self.studentInfoGroup)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.studentFloor = QtWidgets.QLineEdit(parent=self.studentInfoGroup)
        self.studentFloor.setObjectName("studentFloor")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.studentFloor)
        self.verticalLayout_6.addWidget(self.studentInfoGroup)
        self.neighborsGroup = QtWidgets.QGroupBox(parent=self.profile_tab)
        self.neighborsGroup.setObjectName("neighborsGroup")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.neighborsGroup)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.neighborsList = QtWidgets.QListWidget(parent=self.neighborsGroup)
        self.neighborsList.setObjectName("neighborsList")
        self.verticalLayout_7.addWidget(self.neighborsList)
        self.verticalLayout_6.addWidget(self.neighborsGroup)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.tabWidget.addTab(self.profile_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setStyleSheet("color: #2c3e50; font-weight: bold;")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DormHelper - Приложение для общежития"))
        self.newsContent.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#7f8c8d;\">Выберите новость для просмотра...</span></p></body></html>"))
        self.refreshNewsBtn.setText(_translate("MainWindow", "🔄 Обновить новости"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.news_tab), _translate("MainWindow", "📢 Новости и объявления"))
        self.label.setText(_translate("MainWindow", "Тип заявки:"))
        self.requestType.setItemText(0, _translate("MainWindow", "Ремонт в комнате"))
        self.requestType.setItemText(1, _translate("MainWindow", "Сантехника"))
        self.requestType.setItemText(2, _translate("MainWindow", "Электрика"))
        self.requestType.setItemText(3, _translate("MainWindow", "Мебель"))
        self.requestType.setItemText(4, _translate("MainWindow", "Уборка"))
        self.requestType.setItemText(5, _translate("MainWindow", "Другое"))
        self.label_2.setText(_translate("MainWindow", "Описание проблемы:"))
        self.label_3.setText(_translate("MainWindow", "Комната:"))
        self.submitRequestBtn.setText(_translate("MainWindow", "📨 Отправить заявку"))
        self.groupBox.setTitle(_translate("MainWindow", "📋 История моих заявок"))
        item = self.myRequestsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.myRequestsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Тип"))
        item = self.myRequestsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Статус"))
        item = self.myRequestsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Дата"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.requests_tab), _translate("MainWindow", "🔧 Заявки и обращения"))
        self.handbookTree.headerItem().setText(0, _translate("MainWindow", "Разделы"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.handbook_tab), _translate("MainWindow", "📚 Справочник"))
        self.studentInfoGroup.setTitle(_translate("MainWindow", "🎓 Информация о студенте"))
        self.label_4.setText(_translate("MainWindow", "ФИО:"))
        self.label_5.setText(_translate("MainWindow", "Комната:"))
        self.label_6.setText(_translate("MainWindow", "Этаж:"))
        self.neighborsGroup.setTitle(_translate("MainWindow", "👥 Ваша комната"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.profile_tab), _translate("MainWindow", "👤 Личный кабинет"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
